### PR TITLE
rnbw-507: Command shortcut issue

### PR DESCRIPTION
**Pull request by VictoriaShyika**
Fixed issue with typing into input while command shortcuts opens dialog window.

### CODE REVIEW

**Review by jasonliu7040 — COMMENTED** [review]
@VictoriaShyika 
I see the code fixes you made.
but I want to be sure about the reason of the issue. did you notice out?

you know, we defined another cmdk-mechanism inside `StageView - IFrame`, since it's totally different `html - document`.
but the (J,A,W) works correctly in that context.

so please let me know the reason of that issue. thanks.

**Comment by VictoriaShyika** [comment]
@jasonliu7040, `KeyDownEventListener` function reads keys that we press, by opening cmdk dialog using keys, cmds dialog opens but input cmdk also reads key, and set it like search value. 
By adding changes we prevent passing cmdk opening key into input cmdk.

**Comment by jasonliu7040** [comment]
> @jasonliu7040, `KeyDownEventListener` function reads keys that we press, by opening cmdk dialog using keys, cmds dialog opens but input cmdk also reads key, and set it like search value. By adding changes we prevent passing cmdk opening key into input cmdk.

@VictoriaShyika so I am asking that. when you press any key, does it go into cmdk search input automatically?

**Comment by VictoriaShyika** [comment]
@jasonliu7040 
Ohhh, yes its works correct for all keys, when cmdk opened, keys automatically go into cmdk search input.

**Pull request closed without merging**
