### PR TITLE
fixed cut function issue

### PR DESCRIPTION
**Pull request by Aida7788**

### CODE REVIEW

**Comment by atulbhatt-system32** [comment]
@Aida7788 the issue doesn't seem to be resolved. Can you test it again at your end. And can you also describe how you tested it.

Here's a loom how I tested it in a project.

https://www.loom.com/share/1b3f1674751344ab9bfd72856d55fb45?sid=41cd53e8-2eae-4918-8d31-ace768938256

Thanks

**Comment by Aida7788** [comment]
@atulbhatt-system32 
I fixed for new project, not the one you've tested 
image

**Comment by atulbhatt-system32** [comment]
@Aida7788 can you share a loom with that working I have got crash with new project too.

And also, can you explain what the issue was and what change fixed it.

Thanks

**Comment by Aida7788** [comment]
sure @atulbhatt-system32 
I've took  `nodeTree`  which is our main  `tree` object, I have also `selectedItems` , which is my selected file(s), I’ve filtered and have  delated  `selectedItems` object from `nodeTree`  and have updated `setNodeTree`

And the screen recording. [https://www.loom.com/share/b43222979b834f1fb5a78a4b505e8a8b?sid=298c76fa-b2c5-4814-981b-e6706fe96c2c](url)

**Comment by atulbhatt-system32** [comment]
@Aida7788 In the loom I don't see you did cut and paste

Can you show me cut and paste.

For reference you can open and design file in figma. Or maybe create some element in figma like a rectangle.

And then try to cut it and paste it. Also try to copy paste it. And see the difference.

The loom shows example of deleting and copying a node.

You can tell me if I missed something.

Thanks

**Pull request closed without merging**
