### PR TITLE
rnbw-247: code display issue resolved

### PR DESCRIPTION
**Pull request by MadDog1994**

### CODE REVIEW

**Comment by atulbhatt-system32** [comment]
@MadDog1994 please resolve the conflicts

**Comment by atulbhatt-system32** [comment]
image

The selected node on node tree and the code on codeview are not matching. Can you check it.

**Comment by MadDog1994** [comment]
hmm strange, I will check

**Comment by MadDog1994** [comment]
@atulbhatt-system32 could you check pr?

**Pull request merged**
