### PR TITLE
rnbw-357: Code formatting

### PR DESCRIPTION
**Pull request by VictoriaShyika**
Implemented Code Formatting with Command Palette or Shortcut (Ctrl + Shift + F)

### CODE REVIEW

**Comment by jasonliu7040** [comment]
@VictoriaShyika is it completed now?

**Comment by VictoriaShyika** [comment]
It works for formatting by toggle from action panel and shortcut.

**Comment by jasonliu7040** [comment]
@VictoriaShyika 
so we can close this now, right?

**Comment by VictoriaShyika** [comment]
@jasonliu7040  
I think so, but we should keep in mind formatting after actions.

**Pull request merged**
