### PR TITLE
421: Turn into

### PR DESCRIPTION
**Pull request by VictoriaShyika**
Added Turn Into UI in cmdk dialog

### CODE REVIEW

**Review by jasonliu7040 — CHANGES_REQUESTED** [review]
@VictoriaShyika 
now we have constants - `AddFileActionPrefix`, `AddNodeActionPrefix`, `RenameFileActionPrefix`, `RenameNodeActionPrefix`.
the current code uses `RenameActionPrefix` and `AddActionPrefix` which are old ones.
please fix them using the new prefixes.

you can check this 
image

**Comment by VictoriaShyika** [comment]
If we use AddFileActionPrefix, AddNodeActionPrefix, RenameFileActionPrefix, RenameNodeActionPrefix instead of RenameActionPrefix and AddActionPrefix, we must modify command.Context to pass setCurrentCommand correctly.

Maybe I'm misunderstanding the task, the turn into function is supposed to change the name of the node tag, when I select a node and press F2 (or select turn into in the action bar), the turn into panel is displayed and we can select the node to install instead of the selected one. It is right?

**Comment by jasonliu7040** [comment]
yes, @VictoriaShyika . that's correct.

**Comment by VictoriaShyika** [comment]
@jasonliu7040 Just when I test it works as I described.

**Review by jasonliu7040 — APPROVED** [review]

**Comment by VictoriaShyika** [comment]
Good, thanks!

**Pull request merged**
