### PR TITLE
feat: add file searching functionality with s as a shortcut key

### PR DESCRIPTION
**Pull request by ViralRuparel**
**Issue this PR resolves** : [New Feature : Search project files from jumpstart.](https://github.com/rnbwdev/rnbw/issues/709)

**Summary:**
- This PR implements a new Search bar, which can be activated by pressing "s", using `useCmdk`.
- After opening Search bar, when we type something in it, it will look through the files and find the files with the matching name using `useCmdkReferenceSearch`.

**Extras**
- added `search?.toLowerCase()` for all the command dialogs, so it does not consider case sensitivity.

**Recording of the work output**

https://github.com/rnbwdev/rnbw/assets/21654339/8a042969-7c04-45ed-bd01-ab2573dfa70e

### CODE REVIEW

**Comment by atulbhatt-system32** [comment]
Hey @edenvidal  and @ViralRuparel,

I reviewed the PR. The code looks great. Also the extra check added for lowercase is good :).
I also tested the PR code by running it. Below are few things I noticed.

- The files name are shown without there extension. We have extension details also in the fileTree.
image

- Also the files are not opening when clicking selecting them. I'm selecting by pressing "enter" or "clicking" after filtering.
https://github.com/rnbwdev/rnbw/assets/38177419/d12b3e53-6863-40ca-b759-76d2c9713c77

**Comment by edenvidal** [comment]
@ViralRuparel @atulbhatt-system32 , icons are missing.

**Comment by ViralRuparel** [comment]
> @ViralRuparel @atulbhatt-system32 , icons are missing.

I will add that

**Comment by ViralRuparel** [comment]
> Hey @edenvidal and @ViralRuparel,
> 
> I reviewed the PR. The code looks great. Also the extra check added for lowercase is good :). I also tested the PR code by running it. Below are few things I noticed.
> 
> * The files name are shown without there extension. We have extension details also in the fileTree.
> 
> image
> * Also the files are not opening when clicking selecting them. I'm selecting by pressing "enter" or "clicking" after filtering.
>   Though, it was not explicitly mentioned in the Issue to open the files that are searched.
>   https://github.com/rnbwdev/rnbw/assets/38177419/d12b3e53-6863-40ca-b759-76d2c9713c77

okay @atulbhatt-system32  I will retest and fix that.

**Pull request closed without merging**
