### PR TITLE
417: Drag and drop

### PR DESCRIPTION
**Pull request by VictoriaShyika**
Fixed error related with useOnDragOverTreeHandler.
Fixed error with pastCode part while node nesting.

### CODE REVIEW

**Review by jasonliu7040 — CHANGES_REQUESTED** [review]
@VictoriaShyika 
I made changes to Processor by removing some hooks and moving directories, etc.
please have a check and try to fix conflicts.

**Review by jasonliu7040 — CHANGES_REQUESTED** [review]
@VictoriaShyika 
I made changes to Processor by removing some hooks and moving directories, etc.
please have a check and try to fix conflicts.

**Review by jasonliu7040 — CHANGES_REQUESTED** [review]
@VictoriaShyika 
I made changes to Processor by removing some hooks and moving directories, etc.
please have a check and try to fix conflicts.

**Comment by VictoriaShyika** [comment]
This PR is not relevant for the existing dev branch

**Pull request closed without merging**
